2015-02-18 15:00:06,427 ERROR error importing system.processes.py!
2015-02-18 15:13:46,028 ERROR error importing system.processes.py!
2015-02-18 15:13:57,279 ERROR error importing system.processes.py!
2015-02-18 15:14:41,261 ERROR error importing system.processes.py!
2015-02-18 15:21:29,645 ERROR error importing system.processes.py!
2015-02-18 15:22:43,828 ERROR error importing system.processes.py!
2015-02-18 15:24:26,602 ERROR error importing system.processes.py!
2015-02-18 15:24:35,026 ERROR error importing system.processes.py!
2015-02-18 15:27:05,304 ERROR error importing system.processes.py!
2015-02-18 15:27:27,271 ERROR error importing system.processes.py!
2015-02-18 15:29:52,628 ERROR error importing system.processes.py!
2015-02-18 15:37:14,211 ERROR error running disk.py! - check running the plugin with these arguments
2015-02-18 15:37:14,214 ERROR error importing system.processes.py!
2015-02-18 15:38:02,300 ERROR error importing system.processes.py!
2015-02-18 15:38:02,354 ERROR error running redis.py! - check running the plugin with these arguments
2015-02-18 15:41:42,203 ERROR error importing system.processes.py!
2015-02-18 15:41:42,246 ERROR command: "plugins/redis.py --used "4958703616""failed! run the plugin directly to debug.
2015-02-18 15:44:45,210 ERROR error importing system.processes.py!
2015-02-18 15:45:37,517 ERROR error importing system.processes.py!
2015-02-18 15:45:37,557 ERROR command: "plugins/redis.py "failed! run the plugin directly to debug.
2015-02-18 15:46:21,565 ERROR error importing system.processes.py!
2015-02-18 15:46:21,606 ERROR command: "plugins/redis.py {'host': 'localhost', 'port': 3179}"failed! run the plugin directly to debug.
2015-02-18 15:46:56,642 ERROR error importing system.processes.py!
2015-02-18 15:46:56,690 ERROR command: "plugins/redis.py {'host': 'localhost', 'aaa': 'foo', 'port': 3179}"failed! run the plugin directly to debug.
2015-02-18 17:32:23,766 ERROR command: "plugins/processes.py {}"failed! run the plugin directly to debug.
2015-02-18 17:32:32,252 ERROR command: "plugins/processes.py {}"failed! run the plugin directly to debug.
2015-02-18 17:32:40,430 ERROR command: "plugins/processes.py {}"failed! run the plugin directly to debug.
2015-02-18 17:34:09,486 ERROR command: "plugins/processes.py {}"failed! run the plugin directly to debug.
2015-02-18 17:41:01,351 ERROR command: "plugins/processes.py {'name': 'nginx'}"failed! run the plugin directly to debug.
2015-02-18 17:41:46,687 ERROR command: "plugins/processes.py {'procname': 'nginx'}"failed! run the plugin directly to debug.
2015-02-18 17:49:29,310 ERROR command: "plugins/processes.py {'procname': 'nginx'}"failed! run the plugin directly to debug.
2015-02-18 17:49:37,254 ERROR command: "plugins/processes.py {'procname': 'nginx'}"failed! run the plugin directly to debug.
2015-02-18 17:50:05,347 ERROR command: "plugins/processes.py {'procname': 'nginx'}"failed! run the plugin directly to debug.
2015-02-18 17:50:09,761 ERROR command: "plugins/processes.py {'procname': 'nginx'}"failed! run the plugin directly to debug.
2015-02-18 17:50:36,259 ERROR command: "plugins/processes.py {'procname': 'nginx'}"failed! run the plugin directly to debug.
2015-02-18 17:51:01,461 ERROR command: "plugins/processes.py {'procname': 'nginx'}"failed! run the plugin directly to debug.
